name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:

    runs-on: windows-latest

    steps:
      
    - uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v1
      with:
            node-version: 12.8

    - name: install all packages
      working-directory: ./myportfolio
      run: npm install
      
    - name: displaying current directories
      working-directory: ./myportfolio
      run: ls

    - name: install angular cli
      working-directory: ./myportfolio
      run: npm install -g @angular/cli

    - name: build project
      working-directory: ./myportfolio
      run: ng build --prod


